# config/routes/routes.yaml

article_list:
    path: /
    controller: App\Controller\IndexController::home
    methods: GET

new_article:
    path: /article/new
    controller: App\Controller\IndexController::new
    methods: ['GET', 'POST']


article_show:
    path: /article/{id}
    controller: App\Controller\IndexController::show
    methods: ['GET']

edit_article:
    path: /article/edit/{id}
    controller: App\Controller\IndexController::edit
    methods: ['GET', 'POST']

delete_article:
    path: /article/delete/{id}
    controller: App\Controller\IndexController::delete
    methods: ['DELETE']
