homepage:
    path: /
    controller: App\Controller\IndexController::home

article_save:
    path: /article/save
    controller: App\Controller\IndexController::save

new_article:
    path: /article/new
    controller: App\Controller\IndexController::new

article_show:
    path: /article/{id}
    controller: App\Controller\IndexController::show

edit_article:
    path: /article/edit/{id}
    controller: App\Controller\IndexController::edit

delete_article:
    path: /article/delete/{id}
    controller: App\Controller\IndexController::delete
    methods: ['POST']

new_category:
    path: /category/newCat
    controller: App\Controller\IndexController::newCategory

# Route pour la recherche d'articles par catégorie
article_par_cat:
    path: /art_cat/
    controller: App\Controller\IndexController::articlesParCategorie

# Route pour la recherche d'articles par prix
article_par_prix:
    path: /art_prix/
    controller: App\Controller\IndexController::articlesParPrix
